version: "3"

services:
  # transaction_system:
  #   build: src
  #   volumes:
  #     - ./data:/transaction_system/data
  #   ports:
  #     - "5000:5000"
  
  db-api:
    build: ./db/api_server/
    ports:
      - "5000:5000"
    volumes:
      - "./db/api_server:/api_server"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0

  mysql:
    build: ./db/mysql/
    volumes:
      - ./db/mysql/mysql_data:/var/lib/mysql
      - ./db/mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
