version: "3"

services:
  transaction_system:
    build: src
    volumes:
      - ./data:/transaction_system/data
    ports:
      - $TRANS_SYS_PORT:$TRANS_SYS_PORT
    environment:
      - DB_API_PORT=$DB_API_PORT
    depends_on:
      - mysql
      - db-api
  
  db-api:
    build: ./db/api_server/
    ports:
      - $DB_API_PORT:$DB_API_PORT
    volumes:
      - "./db/api_server:/api_server"
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - FLASK_APP=run.py
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0 -p $DB_API_PORT

  mysql:
    build: ./db/mysql/
    volumes:
      - ./db/mysql/mysql_data:/var/lib/mysql
      - ./db/mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - $PHPMYADMIN_PORT:80
    volumes:
      - /sessions
